[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["src"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E501", "E402"]   # E402 allowed because we must call load_dotenv early

[tool.mypy]
python_version = "3.11"
show_error_codes = true
pretty = true
plugins = []
